# frozen_string_literal: true

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

group :test, :development do
  gem 'opentelemetry-api'
  gem 'opentelemetry-exporter-otlp'
  gem 'opentelemetry-sdk'
  gem 'opentelemetry-test-helpers'
end
