source 'https://rubygems.org'
git_source(:github) { |_repo| "https://github.com/#{repo}.git" }

ruby '2.7.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 7.0.1'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '~> 5.0'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri mingw x64_mingw]
end

gem 'aws-sdk-s3', '~> 1'
gem 'faraday'

gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-sdk'

gem 'opentelemetry-propagator-xray'

gem 'opentelemetry-instrumentation-aws_sdk'
gem 'opentelemetry-instrumentation-faraday'
gem 'opentelemetry-instrumentation-rails'
