name: Release ADOT OTLP UDP Exporter
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to tag the release with, e.g., 1.2.0
        required: true

env:
  RUBY_VERSION: "3.2"

jobs:
  build:
    environment: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Contrib Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v4

      # Install ruby and bundle dependencies and cache!
      - name: Install Ruby ${{ env.RUBY_VERSION }} with dependencies
        uses: ruby/setup-ruby@v1.221.0
        with:
          ruby-version: "${{ env.RUBY_VERSION }}"
          working-directory: "exporter/xray-udp"
          bundler: "latest"
          bundler-cache: true
          cache-version: "v1-ruby-xray-udp"

      - name: Run Unit Tests
        run: |
          cd exporter/xray-udp
          bundle install
          bundle exec rake test

      - name: Download and run X-Ray Daemon
        run: |
          mkdir xray-daemon
          cd xray-daemon
          wget https://s3.us-west-2.amazonaws.com/aws-xray-assets.us-west-2/xray-daemon/aws-xray-daemon-linux-3.x.zip
          unzip aws-xray-daemon-linux-3.x.zip
          ./xray -o -n us-west-2 -f ./daemon-logs.log --log-level debug &

      - name: Setup Sample App
        run: |
          cd .github/test-sample-apps/integ-test-http-server/ruby-on-rails
          bundle install

      - name: Run Sample App in Background
        run: |
          cd .github/test-sample-apps/integ-test-http-server/ruby-on-rails
          LISTEN_ADDRESS=127.0.0.1:8080 rails server &
          # Wait for test server to initialize
          sleep 5

      - name: Call Sample App Endpoint
        id: call-endpoint
        run: |
          echo "traceId=$(curl localhost:8080/test)" >> $GITHUB_OUTPUT

      - name: Verify X-Ray daemon received traces
        run: |
          sleep 10
          echo "X-Ray daemon logs:"
          cat xray-daemon/daemon-logs.log
          # Check if the daemon received and processed some data
          if grep -q "sending.*batch" xray-daemon/daemon-logs.log; then
            echo "✅ X-Ray daemon processed trace data (AWS upload errors are expected)"
            exit 0
          elif grep -q "processor:.*segment" xray-daemon/daemon-logs.log; then
            echo "✅ X-Ray daemon processed segment data (AWS upload errors are expected)"
            exit 0
          else
            echo "❌ No evidence of traces being received by X-Ray daemon"
            exit 1
          fi

      # TODO: Publish OTLP UDP Exporter to RubyGems
