name: Release ADOT X-Ray UDP Exporter
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to tag the release with, e.g., 1.2.0
        required: true

env:
  RUBY_VERSION: "3.2"

permissions:
  id-token: write

jobs:
  validate-udp-exporter-e2e-test:
    name: "Validate X-Ray UDP Exporter E2E Test Succeeds"
    uses: ./.github/workflows/udp-exporter-e2e-test.yml
    secrets: inherit
    permissions:
      id-token: write

  release-udp-exporter:
    runs-on: ubuntu-latest
    needs: validate-udp-exporter-e2e-test
    steps:
      - name: Checkout Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v4

      # Install ruby and bundle dependencies and cache!
      - name: Install Ruby ${{ env.RUBY_VERSION }} with dependencies
        uses: ruby/setup-ruby@v1.221.0
        with:
          ruby-version: "${{ env.RUBY_VERSION }}"
          working-directory: "exporter/xray-udp"
          bundler: "latest"
          bundler-cache: true
          cache-version: "v1-ruby-xray-udp"

      - name: Run Unit Tests
        run: |
          cd exporter/xray-udp
          bundle install
          bundle exec rake test

      # TODO: Publish OTLP UDP Exporter to RubyGems
